language: python

sudo: required
services:
  - docker

before_install:
  - docker-compose build

script:
  - docker-compose run web pytest

after_success:
  - bash .travis/deploy_dockerhub.sh
  - bash .travis/deploy_heroku.sh
