version: '3.4'

services:
  web:
    build:
      context: .
      target: oraculi_development
    container_name: oraculi
    volumes:
      - .:/home/webapp
    ports:
      - '5000:5000'
    image: oraculi_development
